### ISSUE TITLE
Ignore superfluous version key with git and path dependencies

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/tools#1800]
And ignore other fields

See https://github.com/dart-lang/pub-dartlang-dart/issues/1348#issuecomment-398428761

This is handled fine by the pub client – but this is worth a warning, I think. Version is ignored!

```yaml
dependencies:
    git: https://github.com/bwhite000/event-listener.git
    version: '>=0.3.0'
```
