### ISSUE TITLE
stream_channel_test fails in dart 2

### ISSUE THREAD

**Issue by jakemac53** [dart-lang/tools#1870]
I spent a fair bit of time digging into this but couldn't figure out the root cause. Somebody else want to take a shot?

```
type '_ControllerStream<dynamic>' is not a subtype of type 'Stream<List<int>>' of 'stream' where
    _ControllerStream is from dart:async
    Stream is from dart:async
    List is from dart:core
    int is from dart:core
  
  package:stream_channel               StreamChannelMixin.transform
  test/stream_channel_test.dart 45:17  main.<fn>
  ===== asynchronous gap ===========================
  dart:async                           _Completer.completeError
  test/stream_channel_test.dart        main.<fn>
  ===== asynchronous gap ===========================
  dart:async                           new Future.microtask
  test/stream_channel_test.dart 43:46  main.<fn>
```

To reproduce you need the following dependency overrides:
```
dependency_overrides:
  analyzer: 0.31.2-alpha.2
  front_end: 0.1.0-alpha.12
  kernel: 0.3.0-alpha.12
  test:
    path: <local-checkout-path>
```

Then you can run `dart --preview-dart-2 test/stream_channel_test.dart `
