### ISSUE TITLE
`wrapAsYamlNode` should apply style recursively

### ISSUE THREAD

**Issue by dcharkes** [dart-lang/tools#1928]
https://pub.dev/documentation/yaml_edit/latest/yaml_edit/wrapAsYamlNode.html

Should this wrap recursively?

input (lists, strings, maps):

`[{name: bla, packaging: dynamic, path: {path_type: absolute, uri: path/with spaces/bla.dll}, target: windows_x64}]`

output:

```
- name: bla
  packaging: dynamic
  path:
    path_type: absolute
    uri: path/with spaces/bla.dll
  target: windows_x64
```

conversion

```dart
String _toYamlString(Object yamlEncoding) => (YamlEditor('')
      ..update(
          [],
          wrapAsYamlNode(
            yamlEncoding,
            collectionStyle: CollectionStyle.BLOCK,
            scalarStyle: ScalarStyle.DOUBLE_QUOTED,
          )))
    .toString();
```

Asked for quotes, but didn't get any.
