### ISSUE TITLE
test_with_coverage not exiting on Windows Github actions with Dart 3.4.0

### ISSUE THREAD

**Issue by dcharkes** [dart-lang/tools#528]
We use the following configuration for GitHub actions to collect coverage.

```yaml
      - name: Install coverage
        run: dart pub global activate coverage

      - name: Collect coverage
        run: dart pub global run coverage:test_with_coverage

      - name: Upload coverage
        uses: coverallsapp/github-action@3dfc5567390f6fa9267c0ee9c251e4c8c3f18949
        with:
          flag-name: ${{ matrix.package }}_${{ matrix.os }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          parallel: true
```

Since a week, the `Collect coverage` step is no longer exiting on the Windows GitHub actions. On Linux and MacOS it's working fine.

* https://github.com/dart-lang/native/issues/1154

Any ideas what's going on?

The last successful run was also on coverage 1.8.0, so I don't believe it's something to do with the coverage package itself.
