### ISSUE TITLE
[coverage] VmService exception at exit on github CI

### ISSUE THREAD

**Issue by liamappelbe** [dart-lang/tools#685]
https://github.com/dart-lang/native/pull/1676
https://github.com/dart-lang/native/actions/runs/11472010902/job/31924474755?pr=1676

The connection is being disposed early. Haven't been able to repro locally. I'll have to debug on CI.

I can add a check to the `service.resume` call, to make sure the service isn't disposed, but I'd like to understand the issue first, otherwise it could mask a bug.

**Comment by talesbarreto** [comment]
Same here. It works just fine on iMac but fails on GitHub Actions.

My config: 

```yaml
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: dart-lang/setup-dart@v1
        with:
          sdk: '3.5.4'
...
      - name: Test
        run: dart run coverage:test_with_coverage
```
 I gave up and switched to Flutter image instead, running the test using `flutter test --coverage`
